symbols=['2GO','AAA','AB','ABA','ABC','ABG','ABS','ABSP','AC',
'ACE','ACPA','ACPB1','ACPB2','ACR','AEV','AGF','AGI','ALCO',
'ALHI','ALI','ALT','ANI','ANS','AP','APC','APO','APX', 'AR',
'ARA','AT', 'ATI','ATN', 'ATNB','AUB', 'BC','BCB','BCOR','BCP',
'BDO','BEL', 'BH','BHI', 'BKR','BLFI', 'BLOOM','BMM', 'BPI',
'BRN', 'BSC','CA', 'CAB','CAL', 'CAT','CDC','CEB','CEI', 'CEU',
'CHI', 'CHIB','CHP', 'CIC','CIP', 'CNPF','COAL', 'COL','COSCO',
'CPG','CPM', 'CPV','CPVB','CROWN','CSB', 'CYBR','DAVIN', 'DD',
'DDPR', 'DFNN', 'DIZ', 'DMC', 'DMCP', 'DMPL', 'DNL', 'DTEL',
'DWC', 'ECP', 'EDC','EEI', 'EG', 'EIBA', 'EIBB', 'ELI', 'EMP',
'EURO', 'EVER', 'EW', 'FAF', 'FDC', 'FEU', 'FFI', 'FGEN',
'FGENF', 'FGENG','FJP', 'FJPB', 'FLI', 'FMETF', 'FNI', 'FOOD',
'FPH', 'FPHP', 'FPHPC', 'FPI', 'FYN', 'FYNB', 'GEO', 'GERI',
'GLO', 'GLOPA','GLOPP', 'GMA7', 'GMAP', 'GPH', 'GREEN', 'GSMI',
'GTCAP', 'H2O', 'HI', 'HLCM', 'HOUSE', 'HVN', 'I', 'ICT', 'IDC',
'IMI','IMP', 'IMPB', 'ION', 'IPM', 'IPO', 'IRC', 'IS', 'ISM',
'JAS', 'JFC', 'JGS', 'JOH', 'KEP', 'KPH', 'KPHB', 'LAND', 'LBC',
'LC', 'LCB', 'LFM', 'LIB', 'LIHC', 'LMG', 'LOTO', 'LPZ', 'LR',
'LRP', 'LRW', 'LSC', 'LTG', 'MA', 'MAB', 'MAC', 'MACAY','MAH',
'MAHB', 'MARC', 'MAXS', 'MB', 'MBC', 'MBT', 'MCP', 'MED', 'MEG',
'MER', 'MFC', 'MFIN', 'MG', 'MGH', 'MHC', 'MJC','MJIC', 'MPI',
'MRC', 'MRSGI', 'MVC', 'MWC', 'MWIDE', 'MWP', 'NI', 'NIKL',
'NOW', 'NRCP', 'NXGEN', 'OM', 'OPM', 'OPMB','ORE', 'OV', 'PA',
'PAL', 'PAX', 'PBB', 'PBC', 'PCOR', 'PCP', 'PERC', 'PF', 'PFP',
'PFP2', 'PGOLD', 'PHA', 'PHC', 'PHES','PHN', 'PIP', 'PLC', 
'PMPC', 'PMT', 'PNB', 'PNC', 'PNX', 'PNX3A', 'PNX3B', 'PNXP',
'POPI', 'PORT', 'PPC', 'PRC', 'PRF2A','PRF2B', 'PRIM', 'PRMX',
'PSB', 'PSE', 'PSPC', 'PTC', 'PTT', 'PX', 'PXP', 'RCB', 'RCI',
'REG', 'RFM', 'RLC', 'RLT','ROCK', 'ROX', 'RRHI', 'RWM', 'SBS',
'SCC', 'SECB', 'SEVN', 'SFI', 'SFIP', 'SGI', 'SGP', 'SHNG',
'SLF', 'SLI', 'SM','SMC', 'SMC2A', 'SMC2B', 'SMC2C', 'SMC2D',
'SMC2E', 'SMC2F', 'SMC2G', 'SMC2H', 'SMC2I', 'SMCP1', 'SMPH',
'SOC', 'SPC','SPH', 'SPM', 'SRDC', 'SSI', 'STI', 'STN', 'STR',
'SUN', 'T', 'TA', 'TAPET', 'TBGI', 'TECH', 'TEL', 'TFC', 'TFHI',
'TLII','TLJJ', 'TUGS', 'UBP', 'UNI', 'UPM', 'URC', 'UW', 'V',
'VITA', 'VLL', 'VMC', 'VUL', 'VVT', 'WEB', 'WIN', 'WPI', 'X',
'YEHEY', 'ZHI']
